site_name: retro-collection-tool
site_description: Igir wrapper for curated ROMM libraries
site_url: https://karl-vanderslice.github.io/retro-collection-tool/
repo_name: karl-vanderslice/retro-collection-tool
repo_url: https://github.com/karl-vanderslice/retro-collection-tool

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Commands: commands.md
  - Architecture: architecture.md
  - TODO: todo.md
